=== kosanovicSW58/XML-projekat/xml-veb-servisi/src/main/resources/data/xsd/z1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
           targetNamespace="http://www.ftn.uns.ac.rs/jaxb/z1"
           xmlns:z1="http://www.ftn.uns.ac.rs/jaxb/z1">

    <xs:element name="zahtev_za_priznanje_ziga">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="informacije_o_ustanovi">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="naziv">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element ref="z1:adresa"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="popunjava_podnosilac">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="1" name="podnosilac" type="z1:TLice"/>
                            <xs:element name="punomocnik" type="z1:TLice"/>
                            <xs:element name="zig">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="vrsta">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="tip_a">
                                                        <xs:complexType>
                                                            <xs:choice>
                                                                <xs:element name="individualni_zig"
                                                                            type="z1:TEmpty" minOccurs="0"/>
                                                                <xs:element name="kolektivni_zig"
                                                                            type="z1:TEmpty" minOccurs="0"/>
                                                                <xs:element name="zig_garancije" type="z1:TEmpty"
                                                                            minOccurs="0"/>
                                                            </xs:choice>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="tip_b">
                                                        <xs:complexType>
                                                            <xs:choice>
                                                                <xs:element name="verbalni_znak" type="z1:TEmpty"
                                                                            minOccurs="0"/>
                                                                <xs:element name="graficki_znak" type="z1:TEmpty"
                                                                            minOccurs="0"/>
                                                                <xs:element name="kombinovani_znak"
                                                                            type="z1:TEmpty" minOccurs="0"/>
                                                                <xs:element name="trodimenzionalni_znak"
                                                                            type="z1:TEmpty" minOccurs="0"/>
                                                                <xs:element name="druga_vrsta" minOccurs="0">
                                                                    <xs:simpleType>
                                                                        <xs:restriction base="xs:string">
                                                                            <xs:minLength value="1"/>
                                                                            <xs:maxLength value="20"/>
                                                                        </xs:restriction>
                                                                    </xs:simpleType>
                                                                </xs:element>
                                                            </xs:choice>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="naznacenje_boje">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:minLength value="1"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element minOccurs="0" name="transliteracija_znak">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:minLength value="1"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element minOccurs="0" name="prevod_znaka">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:minLength value="1"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element minOccurs="0" name="opis_znaka">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:minLength value="1"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="izgled_znaka">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="(.+)/([^/]+)"/>
                                                    <xs:minLength value="0"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="dodatne_informacije">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="klasa_robe_i_uslaga">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element maxOccurs="45" name="klasa">
                                                        <xs:simpleType>
                                                            <xs:restriction base="xs:positiveInteger">
                                                                <xs:maxInclusive value="45"/>
                                                            </xs:restriction>
                                                        </xs:simpleType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="zatrazeno_pravo_prvensta_i_osnov"
                                                    type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="placene_takse">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="osnovna_taksa" type="xs:positiveInteger"/>
                                        <xs:element name="za_klasa">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="naziv_klase" type="xs:string"/>
                                                    <xs:element name="suma" type="xs:positiveInteger"
                                                    />
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="za_graficko_resenje"
                                                    type="xs:positiveInteger"/>
                                        <xs:element name="ukupno" type="xs:positiveInteger"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="popunjava_zavod">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="prilozi_uz_zahtev">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="primerak_znaka" type="z1:TEmpty"
                                                    minOccurs="0"/>
                                        <xs:element name="spisak_robe_i_usluga" type="z1:TEmpty"
                                                    minOccurs="0"/>
                                        <xs:element name="punomocje" type="z1:TEmpty" minOccurs="0"/>
                                        <xs:element name="generalno_punomocje" type="z1:TEmpty"
                                                    minOccurs="0"/>
                                        <xs:element name="punomocje_naknadno_dostavljeno"
                                                    type="z1:TEmpty" minOccurs="0"/>
                                        <xs:element name="opsti_akt" type="z1:TEmpty" minOccurs="0"/>
                                        <xs:element name="dokaz_o_pravu_prvenstva" type="z1:TEmpty"
                                                    minOccurs="0"/>
                                        <xs:element name="dokaz_o_uplati_takse" type="z1:TEmpty"
                                                    minOccurs="0"/>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="broj_prijave_ziga">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="Z-[0-9]{5}/[0-9]{2}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="datum_podnosenja" type="xs:date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="adresa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ulica">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="broj" type="xs:string"/>
                <xs:element name="postanski_broj">
                    <xs:simpleType>
                        <xs:restriction base="xs:positiveInteger">
                            <xs:minInclusive value="11000"/>
                            <xs:maxInclusive value="40000"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="grad">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                            <xs:maxLength value="85"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element minOccurs="0" name="drzava">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:minLength value="1"/>
                            <xs:maxLength value="56"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType abstract="true" name="TLice">
        <xs:sequence>
            <xs:element ref="z1:adresa"/>
            <xs:element name="telefon">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="(\+381|0)6[0-9]{7,8}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="email">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[\w\-\.]+@([\w\-]+\.)+[\w\-]{2,4}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="faks">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TFizicko_lice">
        <xs:complexContent>
            <xs:extension base="z1:TLice">
                <xs:sequence>
                    <xs:element name="ime">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:minLength value="1"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="prezime">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:minLength value="1"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TPoslovno_lice">
        <xs:complexContent>
            <xs:extension base="z1:TLice">
                <xs:sequence>
                    <xs:element name="poslovno_ime" type="xs:string"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TEmpty"/>
</xs:schema>

=== kosanovicSW58/XML-projekat/xml-veb-servisi/src/main/resources/data/xml/z1.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../xsl-fo/zig.xsl"?>
<zahtev_za_priznanje_ziga xmlns="http://www.ftn.uns.ac.rs/jaxb/z1"
                          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                          xsi:schemaLocation="http://www.ftn.uns.ac.rs/jaxb/z1 ../xsd/z1.xsd">
    <informacije_o_ustanovi>
        <naziv>Zavod za intelektualnu svojinu</naziv>
        <adresa>
            <ulica>Knjeginje Ljubice</ulica>
            <broj>5</broj>
            <postanski_broj>11000</postanski_broj>
            <grad>Beograd</grad>
        </adresa>
    </informacije_o_ustanovi>
    <popunjava_podnosilac>
        <podnosilac xsi:type="TFizicko_lice">
            <adresa>
                <ulica>Balzakova</ulica>
                <broj>19</broj>
                <postanski_broj>21000</postanski_broj>
                <grad>Novi Sad</grad>
                <drzava>Srbija</drzava>
            </adresa>
            <telefon>0652587456</telefon>
            <email>sonjas@gmail.com</email>
            <faks>584-985-521</faks>
            <ime>Sonja</ime>
            <prezime>Sonjic</prezime>
        </podnosilac>
        <punomocnik xsi:type="TFizicko_lice">
            <adresa>
                <ulica>Strazilovska</ulica>
                <broj>23</broj>
                <postanski_broj>21000</postanski_broj>
                <grad>Novi Sad</grad>
                <drzava>Srbija</drzava>
            </adresa>
            <telefon>0632548972</telefon>
            <email>miram@gmail.com</email>
            <faks>123-456-789</faks>
            <ime>Mira</ime>
            <prezime>Miric</prezime>
        </punomocnik>
        <zig>
            <vrsta>
                <tip_a>
                    <individualni_zig/>
                </tip_a>
                <tip_b>
                    <graficki_znak/>
                </tip_b>
            </vrsta>
            <naznacenje_boje> Narandzasta, plava</naznacenje_boje>
            <transliteracija_znak > Latinica</transliteracija_znak>
            <prevod_znaka >Cirilica</prevod_znaka>
            <opis_znaka>Krug sa nazivom firme u sredini</opis_znaka>
            <izgled_znaka> C/User/x/home/logo.jpg</izgled_znaka>
        </zig>
        <dodatne_informacije>
            <klasa_robe_i_uslaga>
                <klasa>12</klasa>
                <klasa>45</klasa>
            </klasa_robe_i_uslaga>
            <zatrazeno_pravo_prvensta_i_osnov > Zatrazeno </zatrazeno_pravo_prvensta_i_osnov>
        </dodatne_informacije>
        <placene_takse>
            <osnovna_taksa>1000</osnovna_taksa>
            <za_klasa>
                <naziv_klase> 5 </naziv_klase>
                <suma>1500</suma>
            </za_klasa>
            <za_graficko_resenje>500</za_graficko_resenje>
            <ukupno>3000</ukupno>
        </placene_takse>
    </popunjava_podnosilac>
    <popunjava_zavod>
        <prilozi_uz_zahtev>
            <primerak_znaka/>
            <dokaz_o_uplati_takse/>
            <dokaz_o_pravu_prvenstva/>
        </prilozi_uz_zahtev>
        <broj_prijave_ziga>Z-27190/22</broj_prijave_ziga>
        <datum_podnosenja>2022-07-07</datum_podnosenja>
    </popunjava_zavod>
</zahtev_za_priznanje_ziga>
